using System.ComponentModel.DataAnnotations;

namespace TailorTechAPI.Models
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        // OrderId is auto-generated by the service, not required from client
        public string OrderId { get; set; } = string.Empty;

        [Required]
        public string UserId { get; set; } = string.Empty; // Firebase UID

        [Required]
        public string CustomerName { get; set; } = string.Empty;

        [Required]
        [EmailAddress]
        public string CustomerEmail { get; set; } = string.Empty;

        public string? Phone { get; set; }

        [Required]
        public string DesignType { get; set; } = string.Empty;

        public Dictionary<string, object> Measurements { get; set; } = new();

        public string? SpecialInstructions { get; set; }

        public Dictionary<string, string> ShippingAddress { get; set; } = new();

        public string? GeneratedImage { get; set; }

        public decimal TotalAmount { get; set; }

        [Required]
        public string Status { get; set; } = "pending"; // pending, processing, completed, cancelled

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public DateTime? UpdatedAt { get; set; }
    }
}

